# Generated by Django 5.2.4 on 2025-07-13 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('error', 'Error')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='processedemail',
            name='cleaned_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='to_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_server',
            field=models.CharField(default='imap.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.emailaccount'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='category',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('rejection', 'Rejection'), ('offer', 'Offer'), ('follow_up', 'Follow-Up Needed'), ('newsletter', 'Newsletter'), ('spam', 'Spam'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='processedemail',
            index=models.Index(fields=['category'], name='api_process_categor_f8c769_idx'),
        ),
        migrations.AddField(
            model_name='followupemail',
            name='original_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='api.processedemail'),
        ),
    ]
