# Generated by Django 5.2.4 on 2025-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_followupemail_processedemail_cleaned_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedemail',
            name='category',
            field=models.CharField(blank=True, choices=[('confirmation', 'Confirmation of Application'), ('rejection', 'Rejection'), ('interview', 'Interview'), ('query', 'Query')], max_length=50, null=True),
        ),
    ]
