# Generated by Django 5.0.6 on 2025-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_processedemail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='reprocessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='reprocessing_count',
            field=models.IntegerField(default=0),
        ),
    ]
